Repository codesquad-member-2020/dust-8, pull requests merged in 2020-04, with the labels that each got.

#22 #10 전체 UI 구성 - 미세먼지 수치 탭
  iOS/dust/dust.xcodeproj/project.pbxproj
  iOS/dust/dust.xcodeproj/project.xcworkspace/xcuserdata/hanseop.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/dust/dust/Assets.xcassets/Bad.colorset/Contents.json
  iOS/dust/dust/Assets.xcassets/Good.colorset/Contents.json
  iOS/dust/dust/Assets.xcassets/Normal.colorset/Contents.json
  iOS/dust/dust/Assets.xcassets/Terrible.colorset/Contents.json
  iOS/dust/dust/Base.lproj/Main.storyboard
  iOS/dust/dust/Delegate/AppDelegate.swift
  iOS/dust/dust/Delegate/SceneDelegate.swift
  iOS/dust/dust/Model/DustInfoModel.swift
  iOS/dust/dust/Model/DustInfoModelManager.swift
  iOS/dust/dust/SecondViewController.swift
  iOS/dust/dust/View/Base.lproj/LaunchScreen.storyboard
  iOS/dust/dust/View/Base.lproj/Main.storyboard
  iOS/dust/dust/View/ChartTableView/ChartTableViewCell.swift
  iOS/dust/dust/View/ChartTableView/ChartTableViewDatasource.swift
  iOS/dust/dust/View/ChartTableView/ChartTableViewDelegate.swift
  iOS/dust/dust/View/GradationView.swift
  iOS/dust/dust/ViewController/ChartViewController.swift
  iOS/dust/dust/ViewController/ForecastViewController.swift
Labels: feature

#26 open api로 측정소별 실시간 측정정보 받아오는 기능 구현
  BE/src/main/java/com/codesquad/dust08/controller/StationController.java
Labels: BE, feature

#27 [BE] 특정 측정소에서 측정한 최근 24시간 측정 결과 반환 기능 구현
  BE/src/main/java/com/codesquad/dust08/controller/StationController.java
  BE/src/main/java/com/codesquad/dust08/data/DustStatus.java
  BE/src/main/java/com/codesquad/dust08/data/ResponseResult.java
Labels: BE, feature

#30 [BE] 입력한 위도 경도에서 가장 가까운 측정소 반환 기능 구현
  BE/src/main/java/com/codesquad/dust08/constants/CommonConstants.java
  BE/src/main/java/com/codesquad/dust08/constants/Coordinates.java
  BE/src/main/java/com/codesquad/dust08/constants/UrlConstants.java
  BE/src/main/java/com/codesquad/dust08/controller/StationController.java
  BE/src/main/java/com/codesquad/dust08/data/ResponseResult.java
Labels: BE, feature

#32 [#11] 전체 UI 구성 - 미세먼지 예보 탭
  iOS/dust/dust.xcodeproj/project.pbxproj
  iOS/dust/dust.xcodeproj/project.xcworkspace/xcuserdata/hanseop.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/dust/dust/Info.plist
  iOS/dust/dust/Model/ImageManager.swift
  iOS/dust/dust/Model/NetworkConnection.swift
  iOS/dust/dust/View/Base.lproj/Main.storyboard
  iOS/dust/dust/View/ImageOperation.swift
  iOS/dust/dust/View/PlayButton.swift
  iOS/dust/dust/ViewController/ForecastViewController.swift
Labels: feature

#33 예보 정보 데이터 반환 기능 구현 및 코드 병합
  BE/src/main/java/com/codesquad/dust08/controller/ForecaseController.java
  BE/src/main/java/com/codesquad/dust08/data/ForecaseInformation.java
Labels: BE

#38 [#36] 서버 통신 - 관측소 위치 확인
  iOS/dust/dust.xcodeproj/project.pbxproj
  iOS/dust/dust/Controller/LocationDelegate.swift
  iOS/dust/dust/Controller/LocationManagerDelegate.swift
  iOS/dust/dust/Info.plist
  iOS/dust/dust/Model/DustInfoModel.swift
  iOS/dust/dust/Model/DustInfoModelManager.swift
  iOS/dust/dust/Model/ImageManager.swift
  iOS/dust/dust/Model/NetworkConnection.swift
  iOS/dust/dust/View/Base.lproj/Main.storyboard
  iOS/dust/dust/View/ChartTableView/ChartTableViewDatasource.swift
  iOS/dust/dust/View/ChartTableView/ChartTableViewDelegate.swift
  iOS/dust/dust/ViewController/ChartViewController.swift
Labels: feature

#40 서버 통신 - 미세먼지 정보 및 예보 적용
  iOS/dust/dust.xcodeproj/project.pbxproj
  iOS/dust/dust/Assets.xcassets/나쁨.colorset/Contents.json
  iOS/dust/dust/Assets.xcassets/매우 나쁨.colorset/Contents.json
  iOS/dust/dust/Assets.xcassets/보통.colorset/Contents.json
  iOS/dust/dust/Assets.xcassets/좋음.colorset/Contents.json
  iOS/dust/dust/Extension/DayExtension.swift
  iOS/dust/dust/Model/DustGrade.swift
  iOS/dust/dust/Model/DustInfoModel.swift
  iOS/dust/dust/Model/DustInfoModelManager.swift
  iOS/dust/dust/Model/ForecastModel.swift
  iOS/dust/dust/Model/ImageManager.swift
  iOS/dust/dust/View/Base.lproj/Main.storyboard
  iOS/dust/dust/View/ChartTableView/ChartTableViewDatasource.swift
  iOS/dust/dust/View/ChartTableView/ChartTableViewDelegate.swift
  iOS/dust/dust/View/GradationView.swift
  iOS/dust/dust/View/ImageOperation.swift
  iOS/dust/dust/ViewController/ChartViewController.swift
  iOS/dust/dust/ViewController/ForecastViewController.swift
Labels: feature

#42 배포
  .gitignore
  iOS/dust/dust.xcodeproj/project.pbxproj
  iOS/dust/dust.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/dust/dust.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/dust/dust.xcodeproj/project.xcworkspace/xcuserdata/hanseop.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/dust/dust.xcodeproj/xcuserdata/hanseop.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/dust/dust/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/dust/dust/Assets.xcassets/Contents.json
  iOS/dust/dust/Assets.xcassets/first.imageset/Contents.json
  iOS/dust/dust/Assets.xcassets/first.imageset/first.pdf
  iOS/dust/dust/Assets.xcassets/second.imageset/Contents.json
  iOS/dust/dust/Assets.xcassets/second.imageset/second.pdf
  iOS/dust/dust/Assets.xcassets/나쁨.colorset/Contents.json
  iOS/dust/dust/Assets.xcassets/매우 나쁨.colorset/Contents.json
  iOS/dust/dust/Assets.xcassets/보통.colorset/Contents.json
  iOS/dust/dust/Assets.xcassets/좋음.colorset/Contents.json
  iOS/dust/dust/Controller/LocationDelegate.swift
  iOS/dust/dust/Controller/LocationManagerDelegate.swift
  iOS/dust/dust/Delegate/AppDelegate.swift
  iOS/dust/dust/Delegate/SceneDelegate.swift
  iOS/dust/dust/Extension/DayExtension.swift
  iOS/dust/dust/Info.plist
  iOS/dust/dust/Model/DustGrade.swift
  iOS/dust/dust/Model/DustInfoModel.swift
  iOS/dust/dust/Model/DustInfoModelManager.swift
  iOS/dust/dust/Model/ForecastModel.swift
  iOS/dust/dust/Model/ImageManager.swift
  iOS/dust/dust/Model/NetworkConnection.swift
  iOS/dust/dust/View/Base.lproj/LaunchScreen.storyboard
  iOS/dust/dust/View/Base.lproj/Main.storyboard
  iOS/dust/dust/View/ChartTableView/ChartTableViewCell.swift
  iOS/dust/dust/View/ChartTableView/ChartTableViewDatasource.swift
  iOS/dust/dust/View/ChartTableView/ChartTableViewDelegate.swift
  iOS/dust/dust/View/GradationView.swift
  iOS/dust/dust/View/ImageOperation.swift
  iOS/dust/dust/View/PlayButton.swift
  iOS/dust/dust/ViewController/ChartViewController.swift
  iOS/dust/dust/ViewController/ForecastViewController.swift
  iOS/dust/dustTests/Info.plist
  iOS/dust/dustTests/dustTests.swift
  iOS/readMe.md
Labels: feature

#43 [FE] 미세먼지 탭 기능
  .babelrc
  .gitignore
  FE/js/common/constants.js
  FE/js/common/httpRequest.js
  FE/js/dustView/dustView.js
  FE/js/dustView/render.js
  FE/js/forecastView/render.js
  FE/js/lib/util.js
  FE/js/main.js
  FE/js/model/getDustStatus.js
  FE/js/model/getLocation.js
  FE/style/dust.css
  FE/style/reset.css
  FE/views/dust.html
  package-lock.json
  package.json
  webpack.config.js
Labels: FE, feature, fe리뷰요청

#44 [미세먼지 8조] 리뷰 요청 드립니다.
  .gitignore
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/codesquad/dust08/Dust08Application.java
  BE/src/main/java/com/codesquad/dust08/constants/CommonConstants.java
  BE/src/main/java/com/codesquad/dust08/constants/Coordinates.java
  BE/src/main/java/com/codesquad/dust08/constants/UrlConstants.java
  BE/src/main/java/com/codesquad/dust08/constants/WebConfig.java
  BE/src/main/java/com/codesquad/dust08/controller/ForecaseController.java
  BE/src/main/java/com/codesquad/dust08/controller/StationController.java
  BE/src/main/java/com/codesquad/dust08/data/DustStatus.java
  BE/src/main/java/com/codesquad/dust08/data/ForecaseInformation.java
  BE/src/main/java/com/codesquad/dust08/data/ResponseResult.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/codesquad/dust08/Dust08ApplicationTests.java
  iOS/dust/dust.xcodeproj/project.pbxproj
  iOS/dust/dust.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/dust/dust.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/dust/dust.xcodeproj/project.xcworkspace/xcuserdata/hanseop.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/dust/dust.xcodeproj/xcuserdata/hanseop.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/dust/dust/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/dust/dust/Assets.xcassets/Contents.json
  iOS/dust/dust/Assets.xcassets/first.imageset/Contents.json
  iOS/dust/dust/Assets.xcassets/first.imageset/first.pdf
  iOS/dust/dust/Assets.xcassets/second.imageset/Contents.json
  iOS/dust/dust/Assets.xcassets/second.imageset/second.pdf
  iOS/dust/dust/Assets.xcassets/나쁨.colorset/Contents.json
  iOS/dust/dust/Assets.xcassets/매우 나쁨.colorset/Contents.json
  iOS/dust/dust/Assets.xcassets/보통.colorset/Contents.json
  iOS/dust/dust/Assets.xcassets/좋음.colorset/Contents.json
  iOS/dust/dust/Controller/LocationDelegate.swift
  iOS/dust/dust/Controller/LocationManagerDelegate.swift
  iOS/dust/dust/Delegate/AppDelegate.swift
  iOS/dust/dust/Delegate/SceneDelegate.swift
  iOS/dust/dust/Extension/DayExtension.swift
  iOS/dust/dust/Info.plist
  iOS/dust/dust/Model/DustGrade.swift
  iOS/dust/dust/Model/DustInfoModel.swift
  iOS/dust/dust/Model/DustInfoModelManager.swift
  iOS/dust/dust/Model/ForecastModel.swift
  iOS/dust/dust/Model/ImageManager.swift
  iOS/dust/dust/Model/NetworkConnection.swift
  iOS/dust/dust/View/Base.lproj/LaunchScreen.storyboard
  iOS/dust/dust/View/Base.lproj/Main.storyboard
  iOS/dust/dust/View/ChartTableView/ChartTableViewCell.swift
  iOS/dust/dust/View/ChartTableView/ChartTableViewDatasource.swift
  iOS/dust/dust/View/ChartTableView/ChartTableViewDelegate.swift
  iOS/dust/dust/View/GradationView.swift
  iOS/dust/dust/View/ImageOperation.swift
  iOS/dust/dust/View/PlayButton.swift
  iOS/dust/dust/ViewController/ChartViewController.swift
  iOS/dust/dust/ViewController/ForecastViewController.swift
  iOS/dust/dustTests/Info.plist
  iOS/dust/dustTests/dustTests.swift
  iOS/readMe.md
Labels: BE 리뷰요청
