Repository codesquad-member-2020/dust-8, pull requests merged in 2020-03, with the labels that each got.

#13 [Chore] 프로젝트 초기화
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/codesquad/dust08/Dust08Application.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/codesquad/dust08/Dust08ApplicationTests.java
Labels: BE

#14 #9 전체 UI 구성 - 공통 사항
  .gitignore
  iOS/dust/dust.xcodeproj/project.pbxproj
  iOS/dust/dust.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/dust/dust.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/dust/dust/AppDelegate.swift
  iOS/dust/dust/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/dust/dust/Assets.xcassets/Contents.json
  iOS/dust/dust/Assets.xcassets/first.imageset/Contents.json
  iOS/dust/dust/Assets.xcassets/first.imageset/first.pdf
  iOS/dust/dust/Assets.xcassets/second.imageset/Contents.json
  iOS/dust/dust/Assets.xcassets/second.imageset/second.pdf
  iOS/dust/dust/Base.lproj/LaunchScreen.storyboard
  iOS/dust/dust/Base.lproj/Main.storyboard
  iOS/dust/dust/FirstViewController.swift
  iOS/dust/dust/Info.plist
  iOS/dust/dust/SceneDelegate.swift
  iOS/dust/dust/SecondViewController.swift
  iOS/dust/dustTests/Info.plist
  iOS/dust/dustTests/dustTests.swift
Labels: feature

#20 Feature/be/mockapi
  BE/src/main/java/com/codesquad/dust08/controller/ForecaseController.java
  BE/src/main/java/com/codesquad/dust08/controller/StationController.java
  BE/src/main/resources/application.properties
Labels: BE

#23 #1 프로젝트 기본 설정 및 기본 UI 구성
  .babelrc
  .gitignore
  FE/js/lib/util.js
  FE/style/dust.css
  FE/style/reset.css
  FE/views/dust.html
  package-lock.json
  package.json
  webpack.config.js
Labels: FE, feature
